### PR TITLE
Fix Issue #509

### LINKED ISSUE #509: Species selector on Mutation Sequencer has no description.
Somewhat related to the Mutation Chamber's animal selector issue.
The mutation sequencer also has an animal selector which does not have a description.

### PR DESCRIPTION
**Pull request by Ozyllwynog**
The mutation sequencer has it's own implementation of an animal selector, which does not benefit from the recent addition of descriptions. It is also undesirable to have redundant code that must be maintained separately.
Selection mode allows AnimalSelectorComp to be more capable and future proof.

Mutation sequencer
- Removed animal selector gizmo from and replaced with AnimalSelectorComp instance.
AnimalSelectorComp
- Added selection mode
- Added "NotSequenced" selection mode.
- Added "No Available Choices" option when there are no selectable animals

closes #509

### CODE REVIEW

**Comment by Ozyllwynog** [comment]
I have a few further checks I'd like to make before this is merged.

**Comment by Zeracronius** [comment]
You can always make the PR a draft to prevent merging.

File: Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs [hunk 1]
```diff
@@ -87,20 +89,38 @@ public IEnumerable<PawnKindDef> AllAnimalsSelectable
...
+                IEnumerable<PawnKindDef> animals = Props.AllAnimals;
+
+                // Handle different modes
+                if (Props.selectionMode == "Tagged")
+                {
+                    // All tagged animals
+                    animals = animals.Where(x => Database.TaggedAnimals.Contains(x));
+                
+                }
+                else if (Props.selectionMode == "NotSequenced")
```
Comment (Zeracronius) [inline Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs:101]: I don't like the idea of having a selection mode on a general component that is very sequencer specific. It kind of contradicts the polymorphism and generics.
Instead what you could do is inject the "Not sequenced" filter into the race selector's filter property so that it is the Sequencer that defines how the selector behaves in that specific circumstance.

"SpeciesFilter" callback in this case as "m => !Database.StoredMutations.Contains(m)"

Comment (FxWolfxe) [reply Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs:101]: Agreed, this should be injected into the SpeciesFilter when the parent & comp is initialized not as a string field that is very sequencer specific

**Review by FxWolfxe — CHANGES_REQUESTED** [review]

File: Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs (hunk 1 above)
Comment (Ozyllwynog) [reply Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs:101]: The idea was to provide reusable presets for selection in a centralised location, rather than have each caller define (perhaps redundantly) it's own selection mode. It also allows the selector's configuration to remain in the xml and not be scattered around.

Comment (Zeracronius) [reply Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs:101]: The problem is that if we had 10 things all using the selector in their own way, then you would need 10 different selection modes, all of them only ever used in a single location.
As opposed to each one defining themselves how it should behave and then injecting it.
Dependency injection even if potentially redundant, will still make it easier to maintain since the related code will be kept together. And no specialised behavior logic would be stored inside a generalised component.
