### PR TITLE
Fixed #679 and #643

### LINKED ISSUE #643: Wrong pawn referred in bonded thought.
**Describe the bug**
Nina's bonded thought refers to Nina as being with Nina.

**Screenshots**
billede

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/997532780000968815

### LINKED ISSUE #679: Double master moodlet.
**Describe the bug**
Pet master moodlet appears twice.

**Screenshots**
billede

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/1010639081820139610

### PR DESCRIPTION
**Pull request by Diakon5**
Updates an unused ThoughtWorker and applies to a bugged thought. Adjusts Thought description to avoid base game formatting limitations

**Closing issues**
closes #679 
closes #643

### CODE REVIEW

File: Source/Pawnmorphs/Esoteria/Thoughts/Worker_BeastMaster.cs [hunk 1]
```diff
@@ -23,41 +24,16 @@ public class Worker_BeastMaster : ThoughtWorker
...
         }
 
-
-        private int GetAnimalsCount(Pawn p)
+        protected override bool AnimalMasterCheck(Pawn p, Pawn animal)
         {
-            _animalNames.Clear();
-            GetAnimals(p, _animalNames);
-            return _animalNames.Count;
+            return animal.playerSettings.RespectedMaster == p && animal.IsFormerHuman();
```
Comment (Zeracronius) [inline Source/Pawnmorphs/Esoteria/Thoughts/Worker_BeastMaster.cs:36]: "animal.playerSettings.RespectedMaster == p" can actually be shifted to vanilla by replacing it with "base.AnimalMasterCheck(p, animal)" since that is the entirety of base function.

Comment (FxWolfxe) [reply Source/Pawnmorphs/Esoteria/Thoughts/Worker_BeastMaster.cs:36]: best to use base.AnimalMasterCheck in case any other mods patch that method

Comment (Diakon5) [reply Source/Pawnmorphs/Esoteria/Thoughts/Worker_BeastMaster.cs]: Adjusted

**Review by Zeracronius — APPROVED** [review]
