### PR TITLE
Fix children scaling with the body size patch

### LINKED ISSUE #762: Children are scaled incorrectly when the body size patch is enabled
The body size patch doesn't account for size differences caused by life stage, and so it scales children down on the assumption that they should be as big as adults.

Context: https://discord.com/channels/603713246461165578/603713246461165695/1065851467988226148

### PR DESCRIPTION
**Pull request by RadHazard**
Fixes #762 

Currently, this changes the scale patch to only scale based on the PM_BodySize stat.  In the future it would be preferable to add a mod toggle to swap between that and scaling based on (mod-added) sources of body size changes.

### CODE REVIEW

File: Source/Pawnmorphs/Esoteria/HPatches/Optional/PawnScaling.cs [hunk 1]
```diff
@@ -115,14 +115,15 @@ private static bool TryGetPawnFrameSetPrefix(Pawn pawn)
...
+        // Calculate the scale multiplier based on Pawnmorpher's BodySize multiplier
+        // TODO: Add a toggle to allow scaling by any body size difference compared to normal instead
         [MethodImpl(MethodImplOptions.AggressiveInlining)]
         private static float GetScale(Pawn pawn)
         {
             if (_currentPawn != pawn)
             {
                 _currentPawn = pawn;
-                _currentScaledBodySize = Mathf.Sqrt(pawn.BodySize / pawn.RaceProps.baseBodySize);
+                _currentScaledBodySize = Mathf.Sqrt(StatsUtility.GetStat(pawn, PMStatDefOf.PM_BodySize, 300) ?? 1f);
```
Comment (Zeracronius) [inline Source/Pawnmorphs/Esoteria/HPatches/Optional/PawnScaling.cs:126]: You need to offset it by the pawn's base body size, since the pawn may be 2.0 body size per default, so -20% body size would be 1.6 rather than 0.8.

For regular pawns, their base body size is 1.0, but for aliens it could be anything.

Comment (RadHazard) [reply Source/Pawnmorphs/Esoteria/HPatches/Optional/PawnScaling.cs:126]: Is PM_BodySize not a multiplier?  I was under the assumption that it was always 100% unless a pawn has size-changing mutations.

(incidentally, it would actually have to be `pawn.RaceProps.baseBodySize * pawn.ageTracker.CurLifeStage.bodySizeFactor`.  The missing life stage factor was why it was scaling babies and kids wrong)

Comment (Zeracronius) [reply Source/Pawnmorphs/Esoteria/HPatches/Optional/PawnScaling.cs:126]: You are right.
I was recalling '_currentScaledBodySize' as being the final size, but that is still multiplied on to the current size, so it expects a scale.

**Review by Zeracronius — APPROVED** [review]
