### PR TITLE
Issue 551 - Doors expanded blocks roamer morphs

### LINKED ISSUE #551: [Doors Expanded] Doors blocks any morph of a roaming race.
**Describe the bug**
Expanded doors adds animal check to all doors which require them to be roped to pass through.
If animal has "roamMtbDays" and the door is note defined with "roamerCanOpen" then Expanded Doors will block.
All morphs act as the equivalent animal in this context.

**Mods Involved**
Expanded Doors

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/929297216869384243
https://discord.com/channels/603713246461165578/603713451633803274/929408470845886484

### PR DESCRIPTION
**Pull request by Zeracronius**
Added Doors Expanded door check method to mass patch if present.

**Closing issues**
closes #551

### CODE REVIEW

File: Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs [hunk 1]
```diff
@@ -237,6 +237,13 @@ private static void MassPatchFormerHumanChecks([NotNull] Harmony harmonyInstance
 
             List<MethodInfoSt> methodsToPatch = new List<MethodInfoSt>();
 
+            // Patch doors expanded mod if present.
+            if (LoadedModManager.RunningMods.Any(x => x.PackageId == "jecrell.doorsexpanded"))
+            {
+                methodsToPatch.Add(AccessTools.Method("DoorsExpanded.Building_DoorExpanded:PawnCanOpen"));
```
Comment (FxWolfxe) [inline Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs:243]: I'd add some checks to this if the method isn't found even if the mod is present, I figure a mod is going to have a more volatile API then the base game so some warning if something changes would be good

Comment (Zeracronius) [reply Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs:243]: That is a very good point. Though I think we have null checks later in the code before patching?

That is what triggers the null method warning

Comment (Zeracronius) [reply Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs:243]: Yeah, we have a null check line 314

Comment (FxWolfxe) [reply Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs:243]: I mean a check at 243. if AccessTools returns a null it won't break anything because of the later check but we won't know the Doors Expanded patch isn't working anymore

Comment (Zeracronius) [reply Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs:243]: Right, so you want to be able to tell independently from core methods if a mod integration patch failed.
