### PR TITLE
Issue 774 - paragon aspect not working

### LINKED ISSUE #774: Paragon mutations are not ticking.
**Describe the bug**
Mutations stop progressing at 1 severity even in presence of paragon aspect.

**Screenshots**
billede

**Additional context**
https://discord.com/channels/603713246461165578/615998360045879396/1070637561539735592

### PR DESCRIPTION
**Pull request by Zeracronius**
Paragon aspect did not work because stat cache in Ticker component did not get refreshed.
Seems PostTick method was not getting called?

Moved caches be time based instead of HashTick, and moved stats to use centralized StatsUtility cache.

The problem with IsHashIntervalTick is that it can only be used in a method guaranteed to run every tick, otherwise you may just so happen to never hit the exact tick that counts as hash tick for the pawn.

Now I just say that we can accept up to 300 ticks delay in responsiveness from gaining aspect. (5 seconds at 60tps)

StatsUtility returns null if not not cached and pawn isn't spawned because GetStatValue in that case errors. Coult potentially be changed to return StatDef.defaultBaseValue instead in those cases.

Fixes #774

### CODE REVIEW

File: Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs [hunk 1]
```diff
@@ -244,17 +240,17 @@ public virtual float SeverityChangePerDay()
             if (parent.Severity < minSeverity) sevPerDay = Mathf.Max(0, sevPerDay);
 
 
-            return sevPerDay * Mathf.Max(StatAdjust.Value, 0); //take the mutagen sensitivity stat into account 
+            return sevPerDay * Mathf.Max(StatsUtility.GetStat(Pawn, PMStatDefOf.MutagenSensitivity, 300) ?? 1, 0); //take the mutagen sensitivity stat into account 
         }
 
 
-        internal float EffectiveMax => Mathf.Max(MutationAdaptability.Value, 1) + SeverityOffset;
+        internal float EffectiveMax => Mathf.Max(StatsUtility.GetStat(Pawn, PMStatDefOf.MutationAdaptability, 300) ?? 0, 1) + SeverityOffset;
```
Comment (RadHazard) [inline Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs:247]: Shouldn't the default for MutationAdaptability be 1?  Or are we assuming a pawn can't adapt at all unless they explicitly have the stat?  (I'd appreciate a comment specifying if it's the latter)

File: Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs [hunk 2]
```diff
@@ -185,10 +181,10 @@ public override void CompPostTick(ref float severityAdjustment)
...
             if (Pawn.IsHashIntervalTick(200))
             {
-                StatAdjust.Recalculate();
-                MutationAdaptability.Recalculate();
-                IsReverting.Recalculate();
-                ShouldRemove.Recalculate();
+                //StatAdjust.Recalculate();
+                //MutationAdaptability.Recalculate();
+                //IsReverting.Recalculate();
+                //ShouldRemove.Recalculate();
```
Comment (RadHazard) [inline Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs:187]: These comments can be removed

File: Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs [hunk 3]
```diff
@@ -208,10 +204,10 @@ public void OnStageChanged(HediffStage oldStage, HediffStage newStage)
...
         {
-            StatAdjust.Recalculate();
-            MutationAdaptability.Recalculate();
-            IsReverting.Recalculate();
-            ShouldRemove.Recalculate();
+            //StatAdjust.Recalculate();
+            //MutationAdaptability.Recalculate();
+            //IsReverting.Recalculate();
+            //ShouldRemove.Recalculate();
         }
```
Comment (RadHazard) [inline Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs:211]: This method should either be deprecated or changed to manually flush the cache (depending on what uses it and how important it is for the update to be immediate)

**Comment by RadHazard** [comment]
> Paragon aspect did not work because stat cache in Ticker component did not get refreshed.
> Seems PostTick method was not getting called?

That's very strange... PostTick should always be called every tick for Comps.  Was the hediff itself not ticking, or perhaps throwing exceptions?  (Or maybe there's some issue with `BaseTick = false` causing comps to not tick?)

**Comment by RadHazard** [comment]
> > Paragon aspect did not work because stat cache in Ticker component did not get refreshed.
> > Seems PostTick method was not getting called?
> 
> That's very strange... PostTick should always be called every tick for Comps. Was the hediff itself not ticking, or perhaps throwing exceptions? (Or maybe there's some issue with `BaseTick = false` causing comps to not tick?)

Actually, if PostTick() isn't called, that would mean severity never changes at all because that's where comps affect severity.  Since that wasn't the case AFAIK, that would mean that the problem was in recalculating the cached values themselves.  Though since you've moved to StatsUtility, perhaps the faulty recalculation was fixed anyway.

File: Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs (hunk 1 above)
Comment (Zeracronius) [reply Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs:247]: I checked the stat definition and it's -2 to +2 with a default of 0. Apparently.

**Comment by Zeracronius** [comment]
> > Paragon aspect did not work because stat cache in Ticker component did not get refreshed.
> > Seems PostTick method was not getting called?
> 
> That's very strange... PostTick should always be called every tick for Comps. Was the hediff itself not ticking, or perhaps throwing exceptions? (Or maybe there's some issue with `BaseTick = false` causing comps to not tick?)

As far as I could tell, the maxSeverity was just never updated. So the comp kept thinking the pawns max severity was 1.0 even with paragon aspect bumping it to 3.0.
And I went through each step to verify that the stat values are actually included and accounted for, updating the pawn's stats properly.

I'll have to look into it further in that case, but from what I remember it wasn't PostTick actually changing the severity but the hediff_AddedMutation calling the component instead.

The PostTick here was just to update the cache values.

**Comment by RadHazard** [comment]
Was it perhaps because the mutation was still halted?  They're supposed to un-halt if the paragon aspect is added, but something might have broken that.

Incidentally, the debug string should probably be updated to show whether it's halted and what the current max is.  At the moment it doesn't list either.

**Comment by Zeracronius** [comment]
I can't find anywhere that Halted is being set to true once it hits max severity.

File: Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs [hunk 4]
```diff
@@ -295,7 +284,10 @@ public override string CompDebugString()
             stringBuilder.Append(base.CompDebugString());
             if (!Pawn.Dead)
             {
-                stringBuilder.AppendLine("severity/day: " + SeverityChangePerDay().ToString("F3"));
+                stringBuilder.Append($"severity/day: {SeverityChangePerDay().ToString("F3")}");
+
+                if (_halted)
+                    stringBuilder.Append(" (halted)");
```
Comment (RadHazard) [inline Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs:290]: One last thing I'd like added to this string would be EffectiveMax, so that we can tell for sure if it's being updated properly or not

Comment (Zeracronius) [reply Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs:290]: Good point
