### PR TITLE
Issue 602 - Body purist

### LINKED ISSUE #602: [HAR] Body purist pawns of other races will freak out from race mutations.
**Describe the bug**
A body purist of another race will get a negative mood modifier from every mutation, even those related to their race.

Disable body purist mutation thought for other races? Maybe only for specifically the mutations related to their race?
Thought for missing race-specific mutation?

In this case it is an Orassan replacing Catmorph complaining about catmorph mutations

**Screenshots**
billede

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/987101009698521168

### PR DESCRIPTION
**Pull request by Zeracronius**
Modified mutation thought worker to ignore mutations assigned to race by default.
Affects both body purists and Mutation Affinity. Neither will react to morph influence of their own base species.
This means that to satisfy a Mutation Affinity Orassan, you **have** to use non-"Cat" mutations.
Thoughtworker runs approx. once every 60 ticks. (once per second at x1 speed)
Closes #602

### CODE REVIEW

**Comment by Zeracronius** [comment]
Realised that my solution would nullify Mutation affinity and body purist since they would be considered natural as soon as the pawn shifts into the other race.
Need to ensure that it only counts for those that were originally of that race.

File: Source/Pawnmorphs/Esoteria/Thoughts/Worker_HasMutations.cs [hunk 1]
```diff
@@ -16,34 +19,45 @@ namespace Pawnmorph.Thoughts
...
         /// <param name="p"></param>
         /// <returns></returns>
         protected override ThoughtState CurrentStateInternal(Pawn p)
         {
-            if (!def.IsValidFor(p)) return false;
+            if (!def.IsValidFor(p)) 
+                return ThoughtState.Inactive;
+
             MutationTracker mutTracker = p.GetMutationTracker();
-            if (mutTracker == null) return false;
```
Comment (Zeracronius) [inline Source/Pawnmorphs/Esoteria/Thoughts/Worker_HasMutations.cs:33]: Returning false triggers an implicit cast to ThoughtState.Inactive, so returning that directly should be _slightly_ faster, and I think a bit more readable.
