### PR TITLE
Issue 790 - chaomorph selection

### LINKED ISSUE #790: Chimera morph races are selected randomly instead of by highest influence
**Describe the bug**
When selecting a morph race, if there's no overwhelmingly dominant animal mutation, Pawnmorpher assigns a chimera race instead.  The specific chimera race is intended to be based on the highest-influence animal morph.  However, it's always randomly selected.  This is caused by a minor mistake in tests in MorphUtilities.GetChimeraRace() - the intended behavior is clear, but not working.

**To Reproduce**
1. Create a morph that's 30% iguanamorph, 20% other races.
2. Observe that is race is selected as chaodinomorph only a small percentage of the time.
3. Similar for canid mutations and chaofoxmorphs.

**Error Log**
No error log

**Expected behavior**
Per a plain reading of the code, any primarily-canid type becomes a Chaofoxmorph, any primarily-reptile becomes a Chaodinomorph, a primarily-cow becomes a Chaocowmorph, and a primarily-boomalope becomes a Chaoboommorph.  
My real expectations would be a bit more subtle (30% tiger 20% lynx mutations shouldn't have a chance of making you into a chaoboommorph), but the code at least displays the correct behavior.

### PR DESCRIPTION
**Pull request by Zeracronius**
Closes #790

### CODE REVIEW

File: Source/Pawnmorphs/Esoteria/MorphUtilities.cs [hunk 1]
```diff
@@ -535,29 +535,30 @@ public static bool ShouldBeConsideredHuman([NotNull] this Pawn pawn)
...
+                //if the highest influence isn't a morph pick a random morph from the animal class
+                morph = morph ?? ((AnimalClassDef) hInfluence).GetAllMorphsInClass().RandomElementWithFallback();
             
-            if (morph.classification.Contains(AnimalClassDefOf.Canid)) //TODO Generalize this or just pick randomly, 
-                return MorphDefOfs.ChaofoxMorph;
-            if (morph.classification.Contains(AnimalClassDefOf.Reptile))
-                return MorphDefOfs.ChaodinoMorph;
-            if (morph == MorphDefOfs.BoomalopeMorph) return MorphDefOfs.ChaoboomMorph;
-            if (morph == MorphDefOfs.CowMorph) return MorphDefOfs.ChaocowMorph;
+                // This can happen if the AnimalClassDef doesn't have any associated morphs
```
Comment (RadHazard) [inline Source/Pawnmorphs/Esoteria/MorphUtilities.cs:544]: Since you inverted this if, the comment should probably be clarified that it's referring to morph being null.  Not a huge deal, though.

i.e. `// Morph can be null here if the AnimalClassDef doesn't have any associated morphs`

**Review by RadHazard — APPROVED** [review]
