### PR TITLE
Issue 419 - former human hitching

### LINKED ISSUE #419: Former humans are getting hitched and penned.
**Describe the bug**
Former humans are getting hitched and penned.

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/930717450457186304

### PR DESCRIPTION
**Pull request by Zeracronius**
Added transpiler patch for AnimalPenUtility.GetHitchingPostAnimalShouldBeTakenTo.

**Closing issues**
closes #419

### CODE REVIEW

File: Source/Pawnmorphs/Esoteria/HPatches/AnimalPenUtilityPatches.cs [hunk 1]
```diff
@@ -21,5 +25,51 @@ static void NeedsToBeManagedByRopePatch(Pawn pawn, ref bool __result)
...
+                        if (animalDefFieldRef.opcode != OpCodes.Ldfld || (animalDefFieldRef.operand as FieldInfo) != defField)
+                            continue; // Skip
+
+                        // Replace method call
+                        codes[i].operand = subMethod;
+
+                        // Remove .def
+                        animalDefFieldRef.opcode = OpCodes.Nop;
+                        animalDefFieldRef.operand = null;
+                    }
```
Comment (FxWolfxe) [inline Source/Pawnmorphs/Esoteria/HPatches/AnimalPenUtilityPatches.cs:68]: it's a good idea to break from the loop one you replace the method unless you're replacing several incase the method is modified either in a patch or by another mod's. other then that this looks good
