### PR TITLE
Issue 475 - blank melds

### LINKED ISSUE #475: Events can spawn blank melds.
**Describe the bug**
Melds spawned by events some times don't have any restricted skills and can spawn with all stats set to 0.

Spawning a meld directly with debug tools produces a completely blank unnamed former human meld.
And since melds allow herding, the vanilla herding animal pack can spawn a group of chaomelds completely blank and without backstory allowing them to do everything.

billede

billede

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/941858264956669973

### PR DESCRIPTION
**Pull request by Zeracronius**
Fixed blank melds lacking both skills and background by moving skill transfer to after meld is initialized as former human.

closes #475

### CODE REVIEW

File: Source/Pawnmorphs/Esoteria/DebugUtils/PMDebugActions.cs [hunk 1]
```diff
@@ -363,9 +363,17 @@ static void TryRevertTransformedPawn(Pawn pawn)
...
             var gComp = Find.World.GetComponent<PawnmorphGameComp>();
             (TransformedPawn pawn, TransformedStatus status)? tfPawn = gComp?.GetTransformedPawnContaining(pawn);
+
             TransformedPawn transformedPawn = tfPawn?.pawn;
+
             if (transformedPawn == null || tfPawn?.status != TransformedStatus.Transformed) return;
-            MutagenDef mut = transformedPawn.mutagenDef ?? MutagenDefOf.defaultMutagen;
+
+            MutagenDef mut = null;
+            if (transformedPawn is MergedPawns)
```
Comment (FxWolfxe) [inline Source/Pawnmorphs/Esoteria/DebugUtils/PMDebugActions.cs:372]: TransformedPawn references should really hold a reference of the mutagen that transformed them. but this is fine for now

**Review by FxWolfxe — APPROVED** [review]
